apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-hollybg
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: rollout-hollybg
  strategy:
    blueGreen:
      activeService: rollout-hollybg-active
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        app: rollout-hollybg
    spec:
      containers:
        - image: 'argoproj/rollouts-demo:green'
          imagePullPolicy: Always
          name: rollouts-demo
          ports:
            - containerPort: 8080
