apiVersion: v1
kind: Service
metadata:
  labels:
  name: rollout-hollybg-active
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: rollout-hollybg  
    release: old
